SET (MACSA_VERSION_MAJOR 1)
SET (MACSA_VERSION_MINOR 1)
SET (MACSA_VERSION_PATCH 0)
SET (MACSA_VERSION_REVISION 0)
SET (MACSA_VERSION_REVISION_URL "")

MACRO (MACSA_CREATE_VERSION var)
	SET (MACSA_VERSION_FILENAME "${CMAKE_CURRENT_BINARY_DIR}/Version.h")
	SET (MACSA_VERSION_NAME "${CMAKE_PROJECT_NAME}")
	STRING (TOUPPER "${CMAKE_PROJECT_NAME}" MACSA_VERSION_TAG)
	STRING (REGEX REPLACE "[- .]" "_" MACSA_VERSION_TAG "${MACSA_VERSION_TAG}")

	IF (IS_DIRECTORY ${CMAKE_SOURCE_DIR}/.svn)
		INCLUDE (FindSubversion)
		IF (Subversion_FOUND)
			Subversion_WC_INFO(${CMAKE_SOURCE_DIR} MACSA_VERSION)
			IF (MACSA_VERSION_WC_REVISION)
				SET (MACSA_VERSION_REVISION_ARGS -r "${MACSA_VERSION_WC_REVISION}"
						-u "${MACSA_VERSION_WC_URL}")
			ENDIF ()
		ENDIF ()
	ENDIF ()

	ADD_CUSTOM_COMMAND (OUTPUT "${MACSA_VERSION_FILENAME}"
		COMMAND macsa_versioning
				-f "${MACSA_VERSION_FILENAME}"
				-n "${MACSA_VERSION_NAME}"
				-t "${MACSA_VERSION_TAG}"
				-M "${MACSA_VERSION_MAJOR}"
				-m "${MACSA_VERSION_MINOR}"
				-p "${MACSA_VERSION_PATCH}"
				${MACSA_VERSION_REVISION_ARGS})

	INCLUDE_DIRECTORIES (${CMAKE_CURRENT_BINARY_DIR})
	SET (${var} "${CMAKE_CURRENT_BINARY_DIR}/Version.h")
ENDMACRO ()
