#ifndef PROTOCOL_VERSION_H
#define PROTOCOL_VERSION_H
// SDL Ripper for nisx label
#define PROTOCOL_VERSION_MAJOR		1
#define PROTOCOL_VERSION_MINOR		0
#define PROTOCOL_VERSION_PATCH		0

#define PROTOCOL_VERSION_STR "v1.0.0"
#endif //RIPPER_VERSION_H
